# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tianzhao/quartus_16_fringe_ref/spatial-lang-arria10/gen/DRAMWriteTest/verilog-zynq/project_1/project_1.srcs/sources_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0.xci
# IP: The module: 'design_1_axi_register_slice_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tianzhao/quartus_16_fringe_ref/spatial-lang-arria10/gen/DRAMWriteTest/verilog-zynq/project_1/project_1.srcs/sources_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/tianzhao/quartus_16_fringe_ref/spatial-lang-arria10/gen/DRAMWriteTest/verilog-zynq/project_1/project_1.srcs/sources_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0.xci
# IP: The module: 'design_1_axi_register_slice_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tianzhao/quartus_16_fringe_ref/spatial-lang-arria10/gen/DRAMWriteTest/verilog-zynq/project_1/project_1.srcs/sources_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_register_slice_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
